version: "3.9"

services:
  local-dns:
    build: .                  # build from Dockerfile
    container_name: local-dns
    restart: unless-stopped
    network_mode: "host"      # required to bind to the LAN interface
    volumes:
      - ./dnsmasq/log:/var/log
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dnsmasq/devices.conf:/etc/dnsmasq.d/devices.conf:ro
      - ./dnsmasq/update_device_ips.sh:/etc/dnsmasq.d/update_device_ips.sh:ro
    tty: true