services:
  local-dns:
    build: .                  # build from Dockerfile
    container_name: local-dns
    restart: unless-stopped
    network_mode: "host"      # required to bind to the LAN interface
    volumes:
      - ./dnsmasq/log:/var/log
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dnsmasq/devices.conf:/etc/dnsmasq.d/devices.conf:ro
      - ./dnsmasq/update_device_ips.sh:/etc/dnsmasq.d/update_device_ips.sh:ro
      - ./dnsmasq/generated:/etc/dnsmasq.d/generated
    tty: true

  heartbeat:
    build: ./heartbeat
    container_name: heartbeat
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./heartbeat/.env
    volumes:
      - ./dnsmasq/generated:/shared/dns-configs:ro
      - ./heartbeat/heartbeat.py:/app/heartbeat.py:ro
    depends_on:
      - local-dns


